services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: chatllm_db
      POSTGRES_USER: chatllm_user
      POSTGRES_PASSWORD: chatllm_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatllm_user -d chatllm_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: app
    build:
      context: app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://chatllm_user:chatllm_password@db:5432/chatllm_db?schema=public"
      NEXTAUTH_SECRET: "your-production-secret-key-change-this"
      NEXTAUTH_URL: "http://localhost:3000"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
