name: Pull Request Checks

# This workflow runs on every pull request
on:
  pull_request:
    branches: [ main ]

jobs:
  pr-validation:
    runs-on: ubuntu-latest
    name: PR Validation
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch full history for better diff analysis
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json
          
      - name: Install dependencies
        working-directory: ./app
        run: npm ci
        
      # Check what files were changed
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
            app/**/*.ts
            app/**/*.tsx
            app/**/*.js
            app/**/*.jsx
            app/**/*.json
            app/prisma/**
            
      - name: List changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Changed files:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"
          
      # Run more thorough checks if code files changed
      - name: Run comprehensive tests
        if: steps.changed-files.outputs.any_changed == 'true'
        working-directory: ./app
        run: |
          echo "Running comprehensive validation..."
          npm run lint
          npx prisma generate
          npx tsc --noEmit
          npm run build
          npm run pre-push-check
          
      # Check for common issues
      - name: Check for TODO comments
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Checking for TODO comments in changed files..."
          if grep -r "TODO\|FIXME\|HACK" app/ --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx"; then
            echo "⚠️ Found TODO/FIXME/HACK comments. Consider addressing them."
          else
            echo "✅ No TODO/FIXME/HACK comments found."
          fi
          
      # Check for console.log statements (shouldn't be in production)
      - name: Check for console.log statements
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Checking for console.log statements..."
          if grep -r "console\.log" app/app/ --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx"; then
            echo "⚠️ Found console.log statements. Consider removing them for production."
            exit 1
          else
            echo "✅ No console.log statements found."
          fi
          
      # Check bundle size impact
      - name: Check bundle size
        if: steps.changed-files.outputs.any_changed == 'true'
        working-directory: ./app
        run: |
          echo "Analyzing bundle size..."
          npm run build
          du -sh .next/ || echo "Could not analyze bundle size"
          
      # Add a comment to the PR with results
      - name: Comment PR
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ PR validation completed successfully! All checks passed.'
            })
